apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: 911167912259.dkr.ecr.ap-southeast-2.amazonaws.com/react-app:v1.0.3
        ports:
        - containerPort: 80
