apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: 911167912259.dkr.ecr.ap-southeast-2.amazonaws.com/my-nodejs-app:v1.0.2
        ports:
        - containerPort: 5000
